import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: side-effect import of globals.css without type declarations
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// const BACKGROUND_IMAGE_URL = "/background.jpg";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="antialiased">
				<div className="page-container">
					<main className="">{children}</main>
				</div>
			</body>
		</html>
	);
}
